### ISSUE TITLE
an error occured, see log

### ISSUE THREAD

**Issue by leonfree** [lzoubek/xbmc-plugin-mpdc#16]
Hi,
I got mpd client addon 2.0.7 installed on xbmc 13.1 (gotham). xbmc is launched from *ubuntu14.04 running on an odroid-U3 dev board.

mpdc is configured to connect to a distant mpd server (within the same lan). The connection is ok (the client says it is connected to the mpd server and I can see the playlist entries), but I got "An error occured, see log" and the only possible choice is to exit mpdc. xmbc.log says :

22:57:58 T:2808935456  NOTICE: Connected
22:57:58 T:2808935456  NOTICE: Handling changes - ['mixer', 'playlist', 'player', 'options']
22:58:01 T:2808935456   ERROR: EXCEPTION: argument "label" for method "ListItem" must be unicode or str
22:58:01 T:2808935456   ERROR: Traceback (most recent call last):
22:58:01 T:2808935456   ERROR:   File "/home/odroid/.xbmc/addons/script.mpdc/resources/lib/gui.py", line 219, in _connect
22:58:01 T:2808935456   ERROR:     self._handle_changes(self.client,['mixer','playlist','player','options'])
22:58:01 T:2808935456   ERROR:   File "/home/odroid/.xbmc/addons/script.mpdc/resources/lib/gui.py", line 650, in _handle_changes
22:58:01 T:2808935456   ERROR:     self._update_current_queue(client=poller_client)
22:58:01 T:2808935456   ERROR:   File "/home/odroid/.xbmc/addons/script.mpdc/resources/lib/gui.py", line 255, in _update_current_queue
22:58:01 T:2808935456   ERROR:     listitem = xbmcgui.ListItem( label=item['title'])
22:58:01 T:2808935456   ERROR: TypeError: argument "label" for method "ListItem" must be unicode or str
22:58:01 T:2817324064   ERROR: GetDirectory - Error getting include
22:58:04 T:2808935456  NOTICE: disconnecting
22:58:04 T:2808935456  NOTICE: waiting for poller thread
22:58:04 T:2808935456  NOTICE: done
22:58:04 T:2808935456  NOTICE: disconnecting time poller
22:58:04 T:2808935456  NOTICE: waiting for time poller thread
22:58:04 T:2808935456  NOTICE: done
22:58:04 T:2808935456  NOTICE: client disconnected
22:58:04 T:2808935456   ERROR: CPythonInvoker(10, /home/odroid/.xbmc/addons/script.mpdc/default.py): failed to run the gc to clean up after running prior to shutting do
wn the Interpreter
23:10:31 T:2741826592 WARNING: CPythonInvoker(12, /home/odroid/.xbmc/addons/script.mpdc/default.py): the python script "/home/odroid/.xbmc/addons/script.mpdc/default.py
" has left several classes in memory that we couldn't clean up. The classes include: N14PythonBindings42XBMCAddon_xbmcgui_WindowXMLDialog_DirectorE,N9XBMCAddon9xbmcaddo
n5AddonE,N9XBMCAddon9xbmcaddon5AddonE

It seems the python scripts in script.mpdc/ contain the offending lines. Is the problem related to version of the python (3.7) and/or xbmc (13.1) ? 

Thanks for your work on this addon

lf

**Comment by JesseMFrey** [comment]
I get a similar error when running on my laptop with arch:

>17:40:04 T:140058160740096   DEBUG: ------ Window Init (DialogProgress.xml) ------
>17:40:04 T:140058160740096  NOTICE: Connecting  to  MPD localhost:6600
>17:40:04 T:140057132353280  NOTICE: Starting time poller thread
>17:40:04 T:140058160740096  NOTICE: Connected
>17:40:04 T:140059099351168   DEBUG: ------ Window Init (DialogKaiToast.xml) ------
>17:40:04 T:140058160740096  NOTICE: Handling changes - ['mixer', 'playlist', 'player', 'options']
>17:40:05 T:140058160740096   ERROR: EXCEPTION: argument "value" for method "setProperty" must be unicode or str
>17:40:05 T:140058160740096   ERROR: Traceback (most recent call last):
>17:40:05 T:140058160740096   ERROR:   File "/home/jesse/.kodi/addons/script.mpdc/resources/lib/gui.py", line 219, in _connect
>17:40:05 T:140058160740096   ERROR:     self._handle_changes(self.client,['mixer','playlist','player','options'])
>17:40:05 T:140058160740096   ERROR:   File "/home/jesse/.kodi/addons/script.mpdc/resources/lib/gui.py", line 650, in _handle_changes
>17:40:05 T:140058160740096   ERROR:     self._update_current_queue(client=poller_client)
>17:40:05 T:140058160740096   ERROR:   File "/home/jesse/.kodi/addons/script.mpdc/resources/lib/gui.py", line 258, in _update_current_queue
>17:40:05 T:140058160740096   ERROR:     listitem.setProperty( 'artist', item['artist'] )
>17:40:05 T:140058160740096   ERROR: TypeError: argument "value" for method "setProperty" must be unicode or str

**Comment by azrdev** [comment]
I can confirm the report of @JesseMFrey:
~~~
08:20:38 T:140637182027520   ERROR: EXCEPTION: argument "value" for method "setProperty" must be unicode or str
08:20:38 T:140637182027520   ERROR: Traceback (most recent call last):
08:20:38 T:140637182027520   ERROR:   File "/home/azrdev/.kodi/addons/script.mpdc/resources/lib/gui.py", line 219, in _connect
08:20:38 T:140637182027520   ERROR:     self._handle_changes(self.client,['mixer','playlist','player','options'])
08:20:38 T:140637182027520   ERROR:   File "/home/azrdev/.kodi/addons/script.mpdc/resources/lib/gui.py", line 650, in _handle_changes
08:20:38 T:140637182027520   ERROR:     self._update_current_queue(client=poller_client)
08:20:38 T:140637182027520   ERROR:   File "/home/azrdev/.kodi/addons/script.mpdc/resources/lib/gui.py", line 260, in _update_current_queue
08:20:38 T:140637182027520   ERROR:     listitem.setProperty( 'track',item['track'] )
08:20:38 T:140637182027520   ERROR: TypeError: argument "value" for method "setProperty" must be unicode or str
~~~

**Comment by PeM1664** [comment]
Hi all I've the same kind of error : 
`11:24:44 T:2799150096  NOTICE: PMPDClient
11:24:45 T:2799150096  NOTICE: Connecting  to  MPD 192.168.70.14:6600
11:24:45 T:2799150096  NOTICE: Connected
11:24:45 T:2912678928  NOTICE: Starting time poller thread
11:24:45 T:2799150096  NOTICE: Handling changes - ['mixer', 'playlist', 'player', 'options']
11:24:48 T:2901025808  NOTICE: Thread JobWorker start, auto delete: true
11:24:59 T:2799150096   ERROR: Traceback (most recent call last):
11:24:59 T:2799150096   ERROR:   File "/home/pi/.kodi/addons/script.mpdc/resources/lib/gui.py", line 219, in _connect
11:24:59 T:2799150096   ERROR:     self._handle_changes(self.client,['mixer','playlist','player','options'])
11:24:59 T:2799150096   ERROR:   File "/home/pi/.kodi/addons/script.mpdc/resources/lib/gui.py", line 650, in _handle_changes
11:24:59 T:2799150096   ERROR:     self._update_current_queue(client=poller_client)
11:24:59 T:2799150096   ERROR:   File "/home/pi/.kodi/addons/script.mpdc/resources/lib/gui.py", line 244, in _update_current_queue
11:24:59 T:2799150096   ERROR:     playlist = client.playlistinfo()
11:24:59 T:2799150096   ERROR:   File "/home/pi/.kodi/addons/script.mpdc/resources/lib/rmpd.py", line 16, in <lambda>
11:24:59 T:2799150096   ERROR:     return lambda *args: self._wrap(obj, args)
11:24:59 T:2799150096   ERROR:   File "/home/pi/.kodi/addons/script.mpdc/resources/lib/rmpd.py", line 23, in _wrap
11:24:59 T:2799150096   ERROR:     return func(*args)
11:24:59 T:2799150096   ERROR:   File "/home/pi/.kodi/addons/script.mpdc/resources/lib/xbmpc.py", line 152, in <lambda>
11:24:59 T:2799150096   ERROR:     return lambda *args: wrapper(command, args)
11:24:59 T:2799150096   ERROR:   File "/home/pi/.kodi/addons/script.mpdc/resources/lib/xbmpc.py", line 195, in _execute
11:24:59 T:2799150096   ERROR:     return retval()
11:24:59 T:2799150096   ERROR:   File "/home/pi/.kodi/addons/script.mpdc/resources/lib/xbmpc.py", line 321, in _fetch_songs
11:24:59 T:2799150096   ERROR:     return self._fetch_objects(["file"])
11:24:59 T:2799150096   ERROR:   File "/home/pi/.kodi/addons/script.mpdc/resources/lib/xbmpc.py", line 318, in _fetch_objects
11:24:59 T:2799150096   ERROR:     return self._wrap_iterator(self._read_objects(delimiters))
11:24:59 T:2799150096   ERROR:   File "/home/pi/.kodi/addons/script.mpdc/resources/lib/xbmpc.py", line 290, in _wrap_iterator
11:24:59 T:2799150096   ERROR:     return list(iterator)
11:24:59 T:2799150096   ERROR:   File "/home/pi/.kodi/addons/script.mpdc/resources/lib/xbmpc.py", line 256, in _read_objects
11:24:59 T:2799150096   ERROR:     for key, value in self._read_pairs():
11:24:59 T:2799150096   ERROR:   File "/home/pi/.kodi/addons/script.mpdc/resources/lib/xbmpc.py", line 238, in _read_pairs
11:24:59 T:2799150096   ERROR:     pair = self._read_pair(separator)
11:24:59 T:2799150096   ERROR:   File "/home/pi/.kodi/addons/script.mpdc/resources/lib/xbmpc.py", line 226, in _read_pair
11:24:59 T:2799150096   ERROR:     line = self._read_line()
11:24:59 T:2799150096   ERROR:   File "/home/pi/.kodi/addons/script.mpdc/resources/lib/xbmpc.py", line 211, in _read_line
11:24:59 T:2799150096   ERROR:     raise ConnectionError("Connection lost while reading line")
11:24:59 T:2799150096   ERROR: ConnectionError: Connection lost while reading line
11:25:05 T:2799150096  NOTICE: disconnecting
11:25:05 T:2799150096  NOTICE: waiting for poller thread
11:25:06 T:2799150096  NOTICE: done
11:25:06 T:2799150096  NOTICE: disconnecting time poller
11:25:06 T:2799150096  NOTICE: waiting for time poller thread
11:25:06 T:2799150096  NOTICE: done
11:25:06 T:2799150096  NOTICE: client disconnected
`
What can I do ?
Thanks for your answers
