### ISSUE TITLE
Plugin crashes if playlist contains certain track

### ISSUE THREAD

**Issue by laiti** [lzoubek/xbmc-plugin-mpdc#30]
Plugin crashes immediately when opening if playlist contains the Beatles track "Lovely Rita." I have no idea why, the track doesn't seem to be any different from other tracks. Plugin shows "an error occurred, see log" and quits when I click "OK"

`$ head -1 /home/kodi/.kodi/addons/script.mpdc/changelog.txt
[B]2.0.8[/B]`

`$ mpd --version
Music Player Daemon 0.19.12`

`$ kodi --version
16.1 Git:c327c53 Media Center Kodi`

`$ tail -f /home/kodi/.kodi/temp/kodi.log:
15:03:41 T:140308647573248 WARNING: CSkinInfo: failed to load skin settings
15:03:42 T:140308647573248   ERROR: EXCEPTION: argument "value" for method "setProperty" must be unicode or str
15:03:42 T:140308647573248   ERROR: Traceback (most recent call last):
15:03:42 T:140308647573248   ERROR:   File "/home/kodi/.kodi/addons/script.mpdc/resources/lib/gui.py", line 219, in _connect
15:03:42 T:140308647573248   ERROR:     self._handle_changes(self.client,['mixer','playlist','player','options'])
15:03:42 T:140308647573248   ERROR:   File "/home/kodi/.kodi/addons/script.mpdc/resources/lib/gui.py", line 650, in _handle_changes
15:03:42 T:140308647573248   ERROR:     self._update_current_queue(client=poller_client)
15:03:42 T:140308647573248   ERROR:   File "/home/kodi/.kodi/addons/script.mpdc/resources/lib/gui.py", line 260, in _update_current_queue
15:03:42 T:140308647573248   ERROR:     listitem.setProperty( 'track',item['track'] )
15:03:42 T:140308647573248   ERROR: TypeError: argument "value" for method "setProperty" must be unicode or str
15:03:43 T:140308647573248   ERROR: CPythonInvoker(89, /home/kodi/.kodi/addons/script.mpdc/default.py): failed to run the gc to clean up after running prior to shutting down the Interpreter
15:03:43 T:140308647573248 WARNING: CPythonInvoker(89, /home/kodi/.kodi/addons/script.mpdc/default.py): the python script "/home/kodi/.kodi/addons/script.mpdc/default.py" has left several classes in memory that we couldn't clean up. The classes include: N14PythonBindings42XBMCAddon_xbmcgui_WindowXMLDialog_DirectorE,N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE`

`$ metaflac --list ownCloud/temp/03_-_lovely_rita.flac |grep -v "^[ ]*000"
METADATA block #0
  type: 0 (STREAMINFO)
  is last: false
  length: 34
  minimum blocksize: 4096 samples
  maximum blocksize: 4096 samples
  minimum framesize: 11021 bytes
  maximum framesize: 16036 bytes
  sample_rate: 192000 Hz
  channels: 2
  bits-per-sample: 24
  total samples: 30817920
  MD5 signature: 59eb51c8448de553ff6b3f6e6046d10b
METADATA block #1
  type: 3 (SEEKTABLE)
  is last: false
  length: 306
  seek points: 17
    point 0: sample_number=0, stream_offset=0, frame_samples=4096
    point 1: sample_number=1916928, stream_offset=6253727, frame_samples=4096
    point 2: sample_number=3837952, stream_offset=12832765, frame_samples=4096
    point 3: sample_number=5758976, stream_offset=19460179, frame_samples=4096
    point 4: sample_number=7680000, stream_offset=26028001, frame_samples=4096
    point 5: sample_number=9596928, stream_offset=32647324, frame_samples=4096
    point 6: sample_number=11517952, stream_offset=39337292, frame_samples=4096
    point 7: sample_number=13438976, stream_offset=46038192, frame_samples=4096
    point 8: sample_number=15360000, stream_offset=52668306, frame_samples=4096
    point 9: sample_number=17276928, stream_offset=59320798, frame_samples=4096
    point 10: sample_number=19197952, stream_offset=65987225, frame_samples=4096
    point 11: sample_number=21118976, stream_offset=72649983, frame_samples=4096
    point 12: sample_number=23040000, stream_offset=79295352, frame_samples=4096
    point 13: sample_number=24956928, stream_offset=85980044, frame_samples=4096
    point 14: sample_number=26877952, stream_offset=92526861, frame_samples=4096
    point 15: sample_number=28798976, stream_offset=99057282, frame_samples=4096
    point 16: sample_number=30720000, stream_offset=105573171, frame_samples=4096
METADATA block #2
  type: 4 (VORBIS_COMMENT)
  is last: false
  length: 241
  vendor string: reference libFLAC 1.2.1 20070917
  comments: 9
    comment[0]: ALBUM=Sgt. Pepper’s Lonely Hearts Club Band
    comment[1]: ALBUMARTIST=The Beatles
    comment[2]: ARTIST=The Beatles
    comment[3]: COMPILATION=false
    comment[4]: DATE=1967
    comment[5]: DISCNUMBER=2
    comment[6]: GENRE=Rock
    comment[7]: TITLE=Lovely Rita
    comment[8]: TRACKNUMBER=03
METADATA block #3
  type: 6 (PICTURE)
  is last: false
  length: 97296
  type: 3 (Cover (front))
  MIME type: image/jpeg
  description:
  width: 600
  height: 638
  depth: 24
  colors: 0 (unindexed)
  data length: 97254
  data:
METADATA block #4
  type: 1 (PADDING)
  is last: true
  length: 7991`

**Comment by remschneid** [comment]
Hi,
try to edit and rewrite the Metatags of the song. Sometimes the tags contain some trashy chars and the plugin/python is a little nitpicking,
Hope this helps Rüdiger

**Comment by laiti** [comment]
Hi,

You are right; erasing and re-writing the tags did the trick.

However, I think this should primarily be fixed in mpdc plugin instead of the tags. No matter how bad the input data is, no software should crash.

**Comment by remschneid** [comment]
Hi,

I'll look for a solution, meanwhile happy tagging ;-)

best regards Rüdiger

**Comment by azrdev** [comment]
I can confirm this crash:
~~~
13:00:04.696 T:1531966368   ERROR: EXCEPTION: argument "value" for method "setProperty" must be unicode or str
13:00:04.721 T:1531966368   ERROR: Traceback (most recent call last):
13:00:04.721 T:1531966368   ERROR:   File "/storage/.kodi/addons/script.mpdc/resources/lib/gui.py", line 219, in _connect
13:00:04.723 T:1531966368   ERROR:     self._handle_changes(self.client,['mixer','playlist','player','options'])
13:00:04.723 T:1531966368   ERROR:   File "/storage/.kodi/addons/script.mpdc/resources/lib/gui.py", line 650, in _handle_changes
13:00:04.723 T:1531966368   ERROR:     self._update_current_queue(client=poller_client)
13:00:04.723 T:1531966368   ERROR:   File "/storage/.kodi/addons/script.mpdc/resources/lib/gui.py", line 260, in _update_current_queue
13:00:04.723 T:1531966368   ERROR:     listitem.setProperty( 'track',item['track'] )
~~~

rpi3, LibreELEC 8, Kodi 17, plugin 2.0.8

@remschneid can we help you solving this?

**Comment by mistepien** [comment]
There are no "trashy chars" in tags. Not if mpd can deal with them.
